version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
      - redis  # Добавляем зависимость от Redis
    volumes:
      - .:/app  # Подключаем локальный код для обновления без пересборки
    env_file:
      - .env
    command: ["python3", "bot/bot.py"]  # Явно указываем команду запуска

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: career_quest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres  # Установите пароль для пользователя postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data  # Сохраняем данные между перезапусками
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Автоматическое выполнение init.sql

  redis:
    image: redis:latest  # Используем официальный образ Redis
    restart: always
    ports:
      - "6379:6379"  # Открываем порт Redis
    volumes:
      - redis_data:/data  # Сохраняем данные Redis

volumes:
  pgdata:
  redis_data:  # Создаём volume для Redis
