version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    volumes:
      - .:/app  # Подключаем локальный код для обновления без пересборки
    env_file:
      - .env
    command: ["python3", "bot/bot.py"]  # Явно указываем команду запуска

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: career_quest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres  # Установите пароль для пользователя postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data  # Сохраняем данные между перезапусками
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Добавляем скрипт инициализации

volumes:
  pgdata:
